from knapsack.algorithm import Item

items = [
    Item("Lightsaber", value=95, weight=1.5),
    Item("Tricorder", value=80, weight=1.4),
    Item("Sonic Screwdriver", value=78, weight=0.3),
    Item("Portal Gun", value=92, weight=1.8),
    Item("Infinity Gauntlet", value=100, weight=3.5),
    Item("Babel Fish", value=99, weight=0.01),
    Item("Infinite Improbability Drive", value=100, weight=5.0),
    Item("Hitchhiker's Guide to the Galaxy", value=99, weight=0.9),
    Item("One Ring", value=98, weight=0.1),
    Item("Stark Arc Reactor", value=70, weight=0.9),
    Item("Mjolnir", value=96, weight=4.2),
    Item("Elder Wand", value=94, weight=0.3),
    Item("DeLorean Time Machine", value=100, weight=6.0),
    Item("Lightspeed Travel Manual", value=65, weight=1.3),
    Item("Batman's Utility Belt", value=85, weight=1.0),
    Item("Phaser", value=79, weight=0.8),
    Item("Vibranium Shield", value=88, weight=2.0),
    Item("Magic Mirror", value=82, weight=1.7),
    Item("Witcher Medallion", value=60, weight=0.2),
    Item("Omnitrix", value=91, weight=0.5),
    Item("Gryphon Feather Cloak", value=87, weight=0.6),
    Item("Lightsaber Training Droid", value=74, weight=2.2),
    Item("Turbo-Encabulator", value=97, weight=2.3),
    Item("Quantum Flux Destabilizer", value=88, weight=1.6),
    Item("Phase-Inverted Logic Coupler", value=75, weight=1.2),
    Item("Point-of-Sale Kardashev Transmuter", value=93, weight=0.9),
    Item("Neutrino Soap Dispenser", value=68, weight=0.4),
    Item("Four-Dimensional Coffee Filter", value=81, weight=0.3),
    Item("Asynchronous Hyperthreaded Paradox Resolver", value=98, weight=3.1),
    Item("Reverse-Polarity Ion Shuffler", value=79, weight=1.5),
    Item("Pan-Galactic Calibration Wrench", value=76, weight=2.0),
    Item("Multi-phase Heisenberg Compensator", value=90, weight=1.0),
    Item("Zero-Point Spanner Set (Metric)", value=85, weight=1.8),
    Item("Chrono-Synclastic Infundibulum Stabilizer", value=95, weight=2.6),
    Item("Electrogravitic Flux Re-router", value=87, weight=2.3),
    Item("Overclocked Psionic Cache Buffer", value=89, weight=1.7),
    Item("Non-Euclidean Mousepad", value=65, weight=0.1),
]
